[package]
name = "asahi"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.104", default-features = false }
minreq = { version = "3.0.0", default-features = false }
log = { version = "0.4.34", default-features = false }
zbus = { version = "5.19.0", default-features = false, features = ["async-io", "blocking-api"] }
chrono = { version = "0.4.45", default-features = false, features = ["clock"] }
simple_logger = { version = "5.2.0", default-features = false }
signal-hook = { version = "0.4.4", default-features = false, features = ["iterator"] }
sunrise = { version = "3.0.0", default-features = false, features = ["std"] }
chrono-tz = { version = "0.10.4", default-features = false }
tinyjson = "2.5.1"
boml = "2.0.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

